export const data1=[
    {category_name:"Women Clothes",
     Number_of_products:67,
     image_url:"https://demo.htmlcodex.com/1479/online-shop-website-template/img/cat-1.jpg"
    },
    {category_name:"Mobiles",
     Number_of_products:156,
     image_url:"https://s.yimg.com/os/creatr-uploaded-images/2020-08/f18038e0-e863-11ea-bfb3-a6070684fe31"
    },
    {category_name:"Fruits",
     Number_of_products:37,
     image_url:"https://a0.muscache.com/airbnb/guidebook/v1_grocery_store_hero@2x.jpg"
    },
    {category_name:"Shoes",
     Number_of_products:89,
     image_url:"https://demo.htmlcodex.com/1479/online-shop-website-template/img/cat-3.jpg"
    },
    {category_name:"Camera",
     Number_of_products:127,
     image_url:"https://demo.htmlcodex.com/1479/online-shop-website-template/img/cat-2.jpg"
    },{category_name:"Shampoo",
    Number_of_products:90,
    image_url:"https://demo.htmlcodex.com/1479/online-shop-website-template/img/cat-4.jpg"
   },
   {category_name:"Men",
     Number_of_products:80,
     image_url:"https://i.pinimg.com/originals/5f/58/f0/5f58f03b886de83ae62c0116772aa50c.jpg"
    },{category_name:"Spices",
    Number_of_products:49,
    image_url:"https://www.thelist.com/img/uploads/2016/09/rsz_spices.jpg"
   },{category_name:"Vegetables",
   Number_of_products:34,
   image_url:"https://th.bing.com/th/id/OIP.45SqsEvmzgaGTe0-zaP34wAAAA?rs=1&pid=ImgDetMain"
  },
  {category_name:"Watches",
     Number_of_products:76,
     image_url:"https://th.bing.com/th/id/R.faa4236f01c9458c27af1fef1214199f?rik=4JuGpABWsGdAFQ&riu=http%3a%2f%2fwww.zastavki.com%2fpictures%2foriginals%2f2014%2fBrands____Beautiful_watches_065807_.jpg&ehk=akqyWvVViw5kVAohEcgshnRrzrNO5bufH6aFjEy6m1Y%3d&risl=&pid=ImgRaw&r=0"
    },
    {category_name:"Footwear",
     Number_of_products:57,
     image_url:"https://static.independent.co.uk/s3fs-public/thumbnails/image/2017/07/27/11/lifestyle.jpg"
    },
    {category_name:"Jewellery",
     Number_of_products:39,
     image_url:"https://www.dhanalakshmijewellers.com/wp-content/uploads/2020/09/PearlNecklace-3.jpg"
    }
]